test_conv1d_depthwise, simplify
Also avoid TF error:

InvalidArgumentError: Current implementation only supports equal length strides in the row and column dimensions.

Which is triggered due to the faster depthwise conv kernel.